### PR TITLE
Rails 5 prep

### PR DESCRIPTION
**Pull request by smathy**
Failing a test, but I just want to get this out onto Travis (in case there are other combinations failing).

### CODE REVIEW

**Comment by smathy** [comment]
So interesting, the failure is actually something that should have been failing all along. Might have uncovered a deeper bug with those false positives.

**Comment by ndbroadbent** [comment]
Is the gem ok to use with Rails 5? If not, would you be able to recommend an alternative?

**Comment by smathy** [comment]
Yeah, I haven't had the time to fix those tests, still not sure if it works with R5 or not.  I was going to recommend Pundit, it's what I've been using in recent projects too.

**Comment by smathy** [comment]
I pushed version 3.0 with full Rails5 support the other day.  This PR is now defunct.

**Pull request closed without merging**
