### PR TITLE
Rails 6 support

### PR DESCRIPTION
**Pull request by martijncasteel**
Started working on rails 6 support. I could not get the older versions test of appraisal to work

### CODE REVIEW

**Comment by martijncasteel** [comment]
Fixes #112, @smathy could you review the changes?

**Comment by mainameiz** [comment]
@smathy @be9 could you please look at this PR?

**Comment by d3mash** [comment]
Any progress on this pull request? @smathy @be9

**Comment by smathy** [comment]
Wow, bad @smathy!  SO stale.  I'll make some time to look at it over the weekend.

**Comment by d3mash** [comment]
Hey, we love this gem at our project, but right now it is one of the few things that's blocking us from upgrading to Rails 6 😞 

Could you please take a look at it?

**Comment by ingmaras** [comment]
@smathy it'd be awesome if we could get this merged :)

**Comment by krim** [comment]
@smathy could you look at this PR?

**Comment by belkhiriaa** [comment]
@smathy do you have plans to merge this PR ?

**Comment by belkhiriaa** [comment]
maybe @be9, you have plans ?

**Comment by yvancastilloux** [comment]
@smathy : looking forward to having this merged too.

**Comment by smathy** [comment]
Thanks for your effort @martijncasteel (and for everyone else's encouragement), I finally got around to this.  As I'm sure you all realized, the library itself worked, it was literally just the dependency that needed updating [hangs head in shame] - sorry this took so long.  New 3.2 gem is pushed.

**Comment by smathy** [comment]
...well, and the tests needing some massaging.

**Pull request closed without merging**
